---
title: '4a\. Software Installation Guide'
author: "Z620: Quantitative Biodiversity, Indiana University"
output: pdf_document
geometry: margin = 2.54cm
---

## OVERVIEW

Quantitative Biodiversity (QB) relies on a suite of software (R, RStudio, Git, and LaTeX) that you may want to install on your personal computer.
This guide describes the software and how to install it.

## 1) R

We will use R to manipulate, visualize, and statistically analyze data.
We will install the latest version of R (v 4.2.2; "Innocent and Trusting") using the following instructions:

1. Open a web browser and navigate to the IU CRAN mirror: http://ftp.ussg.iu.edu/CRAN/
2. Select your operating system (Mac, Windows, Linux)
    For Windows Users: install the `base package`
    For Mac Users: install the package for your current version of OS X. You can find out what version is installed by going to the Apple menu and choosing "About This Mac". The version number of OS X you are using appears directly below the words "OS X."
3. The default installation options are recommended for most users

**Mac users please read**:
    The most recent versions of R no longer come packaged with an X11 graphics device.
    Instead, it relies on the program XQuartz for generating plots, etc.
    If you do not already have XQuartz installed, you will need to do this.
    You can download XQuartz v2.8.4 from the following site: http://xquartz.macosforge.org/landing/

## 2) Git

We will be using Git as the version control software to manage our text and code.
If you already use Git, please ensure you are using the most up-to-date version.
If you do not have Git yet installed, please do the following:

1. Open a web browser and navigate to git-scm.com/download/
2. Select the appropriate operating system.
3. The download should start automatically.
4. Open the installer and follow the on-screen directions.

  **On Mac**: You will need to make sure you have Xcode Command Line Tools installed.
  To test this type `which g++` at the command line (i.e., Terminal).
  If you get `/usr/bin/g++` as a reply, then you are ready to move on.
  
  **On Windows**: This process will install Git Bash (msysGit). 
  During installation, you will be asked to adjust your **PATH environment variable**.
  To provide you with the most flexibility, we recommend that you select the option to "Use Git from the Windows Command Prompt".
  In addition, we recommend that during installation you select "Use OpenSSH" for your secure shell client with GitBash.
  
  During installation, you will be asked how to configure the line-ending conversions
  **On Mac**: We recommend "Checkout as-is, commit Unix-style line endings"
  **On Windows**: We recommend "Checkout Windows-style, commit Unix-style line endings"
  
Don't forget, you need to configure Git just as we did in the computer lab. 
Revisit the **'2\. Reproducible Science with Git and GitHub'** Handout.

## 3)  RStudio

We will be using RStudio as the development environment to conduct exercises in R. 
We will also use RStudio to edit and create markdown files. 
If you do not have a current RStudio version installed on your computer, please do the following:

1. Open a web browser and navigate to https://posit.co/download/rstudio-desktop/
2. Select and download the appropriate installer for your operating system (Windows, Mac, Linux)
3. Open the installer and follow the on-screen directions
4. The default installation options are recommended for most users

## 4)  LaTex

Behind the scenes, we will be using the LaTeX typesetting system.
LaTeX will be used by RStudio and the R package **`Knitr`** to convert our RMarkdown files (.Rmd) into professional-quality PDF files. 
This will happen each time we use the "Knit" button in RStudio.
This means that we need to have LaTeX installed, along with a few other packages.   
Note that the `Knitr` conversion will output a .pdf  file with the same name as the processed .Rmd file. This cannot be completed if the target file is being used by another program such as a PDF reader.  

If you do not have LaTeX installed on your computer, please do one of the following: 

**Install TinyTeX**  
This is a cross platform LaTeX distribution developed with R users in mind (<https://yihui.name/tinytex/>). The `tinytex` R package can be used to install TinyTeX from the R console quite easily with the following two commands:  

```{r, eval = FALSE}
#requires web access
install.packages('tinytex') 
tinytex::install_tinytex()
```

During installation a couple of error messages may pop up. 
These may be ignored, just hit the `OK` button and the installation should continue. 
It takes several minutes to complete.
Once the installation is complete you should restart RStudio and check if TinyTex properly installed by typing `tinytex:::is_tinytex()` in the R console. 
If the returned value is `TRUE` you should be good to knit .Rmd files to PDF.

### Alternative installation method  
If for some reason TinyTex fails to install on you machine you can try the following:  
**On a Mac**:

1. Install Basic Tex: https://tug.org/mactex/morepackages.html
2. Note: this will require you to run the commands below (to install `framed` and `titling`).

**On a PC**:

1. Install Basic MiKTeX: http://miktex.org/download.
2. Note: you need to use the MiKTeX package manager to download required style guides.
3. Add folder containing MiKTeX binaries to your **PATH environment variable**

By default, RStudio uses style guides to format our PDF documents. 
These style guides include framed.sty and titling.sty.
We have found that not all LaTeX installations include these style guides.
If you do not have them, you will get an error message when you "Knit".
To fix this, you need to install the required files.
For instructions to add MiKTeX binaries to **PATH environment variable** see https://stackoverflow.com/questions/47911135/r-sweave-no-tex-installation-detected.

**On a Mac**:
Type the following in terminal
    
```sh
tlmgr init-usertree
tlmgr --usermode install framed
tlmgr --usermode install titling
```

The `tlmgr` command should work from any directory if the installation was successful.

If for some reason this does not work (likely due to a permission setting in your operating system or the command PATH wasn't properly loaded during installation), try changing to the MacTex directory (found in the MacTex readme file) to enable `framed` and `titling`. Most likely adding "./", which will indicate to Unix that the command is present in the directory, will allow the `tlmgr` command to function.

```sh
cd /usr/local/texlive/2022/bin/universal-darwin
./tlmgr init-usertree
./tlmgr --usermode install framed
./tlmgr --usermode install titling
```

Adding "sudo", which allows the user to run a command with elevated privileges, may be required to run the `tlmgr` command, depending on your computers administrative permission settings.

```sh
sudo ./tlmgr
```

**On a PC**:
You have two options:
  
1. Open the MikTeX package manager from Start.
2. Search for and install the following: framed, titling
    
    OR
  
1. Type the following in command line (or GitBash):

```sh        
mpm --install framed
mpm --install titling
```